"""
Makefile generation: all Make DSL features.
"""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from dsl import make as mk

# ── Helpers ──────────────────────────────────────────────────────────────────

def section(title):
    print(f"\n{'─'*60}")
    print(f"  {title}")
    print('─'*60)

# ── Variables ────────────────────────────────────────────────────────────────

section("Variable types: MVar, MString, MBool, MArg, special vars")
print("MVar('CC')           :", mk.MVar("CC"))
print("MString('gcc')       :", mk.MString("gcc"))
print("MBool(True)          :", mk.MBool(True))
print("MBool(False)         :", mk.MBool(False))
print("MArg(1)              :", mk.MArg(1))
print("mTargetVar           :", mk.mTargetVar)
print("mFirstPrerequisiteVar:", mk.mFirstPrerequisiteVar)
print("mPrerequisitesVar    :", mk.mPrerequisitesVar)
print("mNULL                :", repr(str(mk.mNULL)))

section("Expression algebra: MAdd, MAnd, MOr, MNot")
A = mk.MVar("HAVE_A")
B = mk.MVar("HAVE_B")
print("MAdd - concatenation:", mk.MAdd(mk.MString("foo"), mk.MString("bar")))
print("MAnd                :", A & B)
print("MOr                 :", A | B)
print("MNot                :", ~A)
print("any_of(A,B,C)       :", mk.any_of(A, B, mk.MVar("C")))
print("all_of(A,B,C)       :", mk.all_of(A, B, mk.MVar("C")))

# ── Assignments ──────────────────────────────────────────────────────────────

section("Assignments: MSet, MSetImmediate, MSetDefault, MAppend")
cc   = mk.MVar("CC")
cxx  = mk.MVar("CXX")
cflags = mk.MVar("CFLAGS")
ldflags = mk.MVar("LDFLAGS")
srcs = mk.MVar("SRCS")

for node in [
    mk.MSet(cc, mk.MString("gcc")),
    mk.MSetImmediate(cxx, mk.MString("g++")),
    mk.MSetDefault(cflags, mk.MString("-O2 -Wall")),
    mk.MAppend(cflags, mk.MString("-g")),
]:
    print(node)

section("MAssignmentList — column-aligned")
alist = mk.MAssignmentList(
    mk.MSet(mk.MVar("CC"),      mk.MString("gcc")),
    mk.MSet(mk.MVar("CXX"),     mk.MString("g++")),
    mk.MSetDefault(mk.MVar("CFLAGS"),   mk.MString("-O2")),
    mk.MSetDefault(mk.MVar("LDFLAGS"),  mk.MString("")),
    mk.MSetImmediate(mk.MVar("BUILDDIR"), mk.MString("build")),
)
print(alist)

# ── Rules ────────────────────────────────────────────────────────────────────

section("Rules: MStaticRule, MIndependentRule, MGroupedRule, MPhony")
print(mk.MStaticRule(mk.MString("foo"), prereqs=mk.MString("bar baz")))
print(mk.MIndependentRule(mk.MString("foo"), prereqs=mk.MString("bar")))
print(mk.MGroupedRule(mk.MAdd(mk.MString("foo"), mk.MString("bar")), prereqs=mk.MString("dep")))
print(mk.MPhony(mk.MString("all clean")))

section("MRecipe — rule + indented commands")
recipe = mk.MRecipe(
    mk.MStaticRule(mk.MString("$(BUILDDIR)/app"), prereqs=mk.MString("$(OBJS)")),
    mk.MCommand("$(CC)", "$(CFLAGS)", "-o", mk.mTargetVar, mk.mPrerequisitesVar, flags=mk.MFlag.SILENT),
    mk.MCommand("echo", "Built $@"),
)
print(recipe)

section("MCommand flags: SILENT, IGNORE_ERRORS, ALWAYS")
for flag in [mk.MFlag.NONE, mk.MFlag.SILENT, mk.MFlag.IGNORE_ERRORS, mk.MFlag.ALWAYS,
             mk.MFlag.SILENT | mk.MFlag.IGNORE_ERRORS]:
    cmd = mk.MCommand("make", "-C", "subdir", flags=flag)
    print(f"  {str(flag)!r:20s} => {cmd}")

# ── Comments, MText ───────────────────────────────────────────────────────────

section("MComment and MText")
print(mk.MComment("Generated by DSL"))
print(mk.MText("raw line goes here"))

# ── Include ──────────────────────────────────────────────────────────────────

section("MInclude")
print(mk.MInclude("config.mk"))
print(mk.MInclude("path with spaces/rules.mk", "second.mk"))

# ── Define block ─────────────────────────────────────────────────────────────

section("MDefine / MENDEF")
from dsl.make.block import MDefine
define_node = MDefine(
    mk.MVar("COMPILE_CMD"),
    mk.MText("$(CC) $(CFLAGS) -c $< -o $@"),
    mk.MText("@echo ' CC  $@'"),
)
print(define_node)

# ── Functions ────────────────────────────────────────────────────────────────

section("Make functions: MIfFunc, MShellFunc, MCallFunc, MForeachFunc, MEvalFunc")
print("MIfFunc  :", mk.MIfFunc(mk.MVar("DEBUG"), mk.MString("-g"), mk.MString("")))
print("MShellFunc:", mk.MShellFunc(mk.MString("uname -m")))
print("MCallFunc :", mk.MCallFunc(mk.MVar("compile"), mk.MVar("SRCS")))
print("MForeachFunc:", mk.MForeachFunc(
    mk.MVar("f"),
    mk.MVar("SRCS"),
    mk.MAdd(mk.MString("$(BUILDDIR)/"), mk.MAdd(mk.MVar("f"), mk.MString(".o"))),
))
print("MEvalFunc :", mk.MEvalFunc(mk.MString("$(OBJS): $(HDRS)")))

# ── Conditionals ─────────────────────────────────────────────────────────────

section("Standalone conditionals: MIf, MIfDef, MIfNDef, MIfEq, MIfNEq")
print(mk.MIfDef(mk.MVar("DEBUG"),
    mk.MSet(mk.MVar("CFLAGS"), mk.MString("-g -O0")),
))
print()
print(mk.MIfEq(mk.MVar("ARCH"), mk.MString("arm"),
    mk.MSet(mk.MVar("CROSS_COMPILE"), mk.MString("arm-linux-gnueabihf-")),
))

section("MConditionList — if / else ifdef / else chain")
chain = mk.MConditionList(
    mk.MIf(mk.MVar("RELEASE"),
        mk.MSet(mk.MVar("CFLAGS"), mk.MString("-O3 -DNDEBUG")),
    ),
    mk.MIfDef(mk.MVar("DEBUG"),
        mk.MSet(mk.MVar("CFLAGS"), mk.MString("-g -O0 -DDEBUG")),
    ),
    mk.MElse(
        mk.MSet(mk.MVar("CFLAGS"), mk.MString("-O2")),
    ),
)
print(chain)

# ── Full Makefile ─────────────────────────────────────────────────────────────

section("Full Makefile example")
mf = mk.Makefile(
    mk.MComment("C project — generated by DSL"),

    mk.MAssignmentList(
        mk.MSet(mk.MVar("CC"),       mk.MString("gcc")),
        mk.MSetDefault(mk.MVar("CFLAGS"),   mk.MString("-O2 -Wall")),
        mk.MSetDefault(mk.MVar("LDFLAGS"),  mk.MString("")),
        mk.MSetImmediate(mk.MVar("BUILDDIR"), mk.MString("build")),
        mk.MSetImmediate(mk.MVar("SRCS"),   mk.MShellFunc(mk.MString("find src -name '*.c'"))),
        mk.MSetImmediate(mk.MVar("OBJS"),   mk.MForeachFunc(
            mk.MVar("s"), mk.MVar("SRCS"),
            mk.MAdd(mk.MVar("BUILDDIR"), mk.MAdd(mk.MString("/"), mk.MAdd(mk.MVar("s"), mk.MString(".o")))),
        )),
    ),

    mk.MConditionList(
        mk.MIfDef(mk.MVar("DEBUG"),
            mk.MAppend(mk.MVar("CFLAGS"), mk.MString("-g -O0")),
        ),
        mk.MElse(
            mk.MAppend(mk.MVar("CFLAGS"), mk.MString("-DNDEBUG")),
        ),
    ),

    mk.MPhony(mk.MString("all clean")),

    mk.MRecipe(
        mk.MStaticRule(mk.MString("all"), prereqs=mk.MString("$(BUILDDIR)/app")),
    ),

    mk.MRecipe(
        mk.MStaticRule(
            mk.MString("$(BUILDDIR)/app"),
            prereqs=mk.MString("$(OBJS)"),
        ),
        mk.MCommand("$(CC)", "$(LDFLAGS)", "-o", mk.mTargetVar, mk.mPrerequisitesVar,
                    flags=mk.MFlag.SILENT),
        mk.MCommand("echo", "Linked $@"),
    ),

    mk.MRecipe(
        mk.MStaticRule(
            mk.MString("$(BUILDDIR)/%.c.o"),
            prereqs=mk.MString("%.c"),
        ),
        mk.MCommand("mkdir", "-p", "$(dir $@)", flags=mk.MFlag.SILENT),
        mk.MCommand("$(CC)", "$(CFLAGS)", "-c", mk.mFirstPrerequisiteVar, "-o", mk.mTargetVar,
                    flags=mk.MFlag.SILENT),
    ),

    mk.MRecipe(
        mk.MStaticRule(mk.MString("clean")),
        mk.MCommand("rm", "-rf", "$(BUILDDIR)", flags=mk.MFlag.SILENT | mk.MFlag.IGNORE_ERRORS),
    ),
)
print(mf)
